package com.indiesoundquest.tournament.domain;
import jakarta.persistence.*; import java.util.UUID;
@Entity @Table(name="tournament_match") public class TournamentMatch {
 @Id private UUID id; @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="tournament_id",nullable=false) private Tournament tournament;
 @Column(name="round_number",nullable=false) private int roundNumber; @Column(name="match_index",nullable=false) private int matchIndex;
 @Column(name="left_entry_id") private UUID leftEntryId; @Column(name="right_entry_id") private UUID rightEntryId; @Column(name="winner_entry_id") private UUID winnerEntryId;
 @Column(name="next_match_id") private UUID nextMatchId; @Column(name="next_slot") private String nextSlot; @Enumerated(EnumType.STRING) @Column(nullable=false) private MatchStatus status; @Version private long version;
 protected TournamentMatch(){} public static TournamentMatch planned(UUID id,Tournament t,int round,int index,UUID left,UUID right,UUID next,String slot){var m=new TournamentMatch();m.id=id;m.tournament=t;m.roundNumber=round;m.matchIndex=index;m.leftEntryId=left;m.rightEntryId=right;m.nextMatchId=next;m.nextSlot=slot;m.status=MatchStatus.PENDING;return m;} public void complete(UUID entry){if(status!=MatchStatus.PENDING||!entry.equals(leftEntryId)&&!entry.equals(rightEntryId))throw new IllegalStateException("invalid vote");winnerEntryId=entry;status=MatchStatus.COMPLETED;} public void placeWinner(UUID entry,String slot){if("LEFT".equals(slot))leftEntryId=entry;else rightEntryId=entry;} public UUID getId(){return id;} public Tournament getTournament(){return tournament;} public int getRoundNumber(){return roundNumber;} public int getMatchIndex(){return matchIndex;} public UUID getLeftEntryId(){return leftEntryId;} public UUID getRightEntryId(){return rightEntryId;} public MatchStatus getStatus(){return status;} public UUID getWinnerEntryId(){return winnerEntryId;} public UUID getNextMatchId(){return nextMatchId;} public String getNextSlot(){return nextSlot;}
}
