package com.indiesoundquest.agent.web;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.indiesoundquest.agent.application.AgentRunApplicationService;
import com.indiesoundquest.agent.application.AgentRunFollowUpApplicationService;
import com.indiesoundquest.agent.domain.AgentRunEventType;
import com.indiesoundquest.conversation.application.*;
import com.indiesoundquest.tournament.application.CandidatePoolApplicationService;
import com.indiesoundquest.tournament.application.PreferenceReportApplicationService;
import java.util.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.web.bind.annotation.*;
import org.springframework.transaction.annotation.Transactional;

@RestController
@RequestMapping("/internal/v1/agent-runs")
public class AgentWorkerInternalController {
  private final AgentRunApplicationService runs; private final AgentRunFollowUpApplicationService followUps; private final ConversationApplicationService conversations; private final CandidatePoolApplicationService candidatePools; private final PreferenceReportApplicationService reports; private final ObjectMapper json; private final String token;
  public AgentWorkerInternalController(AgentRunApplicationService runs,AgentRunFollowUpApplicationService followUps,ConversationApplicationService conversations,CandidatePoolApplicationService candidatePools,PreferenceReportApplicationService reports,ObjectMapper json,@Value("${agent.internal.service-token}")String token){this.runs=runs;this.followUps=followUps;this.conversations=conversations;this.candidatePools=candidatePools;this.reports=reports;this.json=json;this.token=token;}
  private void authorize(String value){if(!Objects.equals(value,"Bearer "+token))throw new org.springframework.web.server.ResponseStatusException(HttpStatus.UNAUTHORIZED);}

  @PostMapping("/{id}/claim") LeaseView claim(@PathVariable UUID id,@RequestHeader("Authorization")String auth,@RequestBody Worker body){authorize(auth);var lease=runs.claim(id,body.workerId());return new LeaseView(lease.attemptNo(),lease.leaseToken());}
  @PostMapping("/{id}/heartbeat") void heartbeat(@PathVariable UUID id,@RequestHeader("Authorization")String auth,@RequestHeader("X-Lease-Token")String lease){authorize(auth);runs.heartbeat(id,lease);}
  @PostMapping("/{id}/interventions") InterventionBatch interventions(@PathVariable UUID id,@RequestHeader("Authorization")String auth,@RequestHeader("X-Lease-Token")String lease,@RequestBody InterventionCursor body){authorize(auth);if(body.afterSequence()<0)throw new IllegalArgumentException("afterSequence must be non-negative");var items=runs.interventionsAfter(id,lease,body.afterSequence()).stream().map(InterventionView::of).toList();return new InterventionBatch(items);}
  @PostMapping("/{id}/interventions/applied") Map<String,Object> interventionsApplied(@PathVariable UUID id,@RequestHeader("Authorization")String auth,@RequestHeader("X-Lease-Token")String lease,@RequestBody InterventionApplied body){authorize(auth);if(body.throughSequence()<1)throw new IllegalArgumentException("throughSequence must be positive");return Map.of("appliedCount",runs.markInterventionsApplied(id,lease,body.throughSequence()),"throughSequence",body.throughSequence());}
  @PostMapping("/{id}/events") void event(@PathVariable UUID id,@RequestHeader("Authorization")String auth,@RequestHeader("X-Lease-Token")String lease,@RequestBody Event body){authorize(auth);runs.assertLease(id,lease);var type=switch(body.type()){case "plan_updated"->AgentRunEventType.PLAN_UPDATED;case "commentary"->AgentRunEventType.COMMENTARY;case "tool_started"->AgentRunEventType.TOOL_STARTED;case "tool_completed"->AgentRunEventType.TOOL_COMPLETED;case "tool_degraded"->AgentRunEventType.TOOL_DEGRADED;case "response_started"->AgentRunEventType.RESPONSE_STARTED;case "response_delta"->AgentRunEventType.RESPONSE_DELTA;case "progress"->AgentRunEventType.PROGRESS;default->throw new IllegalArgumentException("UNSUPPORTED_AGENT_EVENT");};runs.appendEvent(id,type,body.payloadJson());}
  @PostMapping("/{id}/complete") @Transactional void complete(@PathVariable UUID id,@RequestHeader("Authorization")String auth,@RequestHeader("X-Lease-Token")String lease,@RequestBody Completion body){authorize(auth);runs.assertLease(id,lease);var artifact=new LinkedHashMap<String,Object>();artifact.put("traceSummary",body.traceSummary()==null?Map.of():body.traceSummary());if(body.card()!=null)artifact.put("card",body.card().payload());runs.complete(id,write(artifact));var card=body.card()==null?null:new ConversationAgentGateway.Card(body.card().messageType(),body.card().cardType(),write(body.card().payload()));var result=new ConversationAgentGateway.Result(body.text(),card,body.memorySummary(),body.memorySummaryThroughSequence());conversations.complete(body.conversationId(),id,result);runs.finishLease(id,lease);followUps.dispatch(id);}
  @PostMapping("/{id}/waiting") void waiting(@PathVariable UUID id,@RequestHeader("Authorization")String auth,@RequestHeader("X-Lease-Token")String lease,@RequestBody Waiting body){authorize(auth);runs.assertLease(id,lease);var card=new ConversationAgentGateway.Card(body.card().messageType(),body.card().cardType(),write(body.card().payload()));conversations.completeWaitingForUser(body.conversationId(),id,new ConversationAgentGateway.Result(body.text(),card,null,null),body.snapshot());runs.finishLease(id,lease);}
  @PostMapping("/{id}/complete-candidate") void completeCandidate(@PathVariable UUID id,@RequestHeader("Authorization")String auth,@RequestHeader("X-Lease-Token")String lease,@RequestBody CandidateCompletion body){authorize(auth);runs.assertLease(id,lease);try{var normalized=candidatePools.fromAgentResult(id,body.size(),json.readTree(body.resultJson()),body.seedArtistIds());runs.complete(id,write(normalized));runs.finishLease(id,lease);}catch(Exception e){throw new IllegalArgumentException("CANDIDATE_RESULT_INVALID",e);}}
  @PostMapping("/{id}/report-started") void reportStarted(@PathVariable UUID id,@RequestHeader("Authorization")String auth,@RequestHeader("X-Lease-Token")String lease,@RequestBody ReportRef body){authorize(auth);reports.markAgentRunRunning(id,lease,body.reportId());}
  @PostMapping("/{id}/complete-report") void completeReport(@PathVariable UUID id,@RequestHeader("Authorization")String auth,@RequestHeader("X-Lease-Token")String lease,@RequestBody ReportCompletion body){authorize(auth);reports.completeAgentRun(id,lease,body.reportId(),body.resultJson());}
  @PostMapping("/{id}/fail-report") void failReport(@PathVariable UUID id,@RequestHeader("Authorization")String auth,@RequestHeader("X-Lease-Token")String lease,@RequestBody ReportFailure body){authorize(auth);reports.failAgentRun(id,lease,body.reportId(),body.code(),body.message());}
  @PostMapping("/{id}/fail") @Transactional void fail(@PathVariable UUID id,@RequestHeader("Authorization")String auth,@RequestHeader("X-Lease-Token")String lease,@RequestBody Failure body){authorize(auth);runs.assertLease(id,lease);runs.fail(id,write(Map.of("code",body.code(),"message",body.message())));runs.finishLease(id,lease);followUps.dispatch(id);}
  @PostMapping("/{id}/retry") void retry(@PathVariable UUID id,@RequestHeader("Authorization")String auth,@RequestHeader("X-Lease-Token")String lease,@RequestBody Failure body){authorize(auth);runs.retry(id,lease,body.code());}
  private String write(Object value){try{return json.writeValueAsString(value);}catch(Exception e){throw new IllegalArgumentException(e);}}
  @ExceptionHandler(IllegalStateException.class) ResponseEntity<Void> conflict(){return ResponseEntity.status(HttpStatus.CONFLICT).build();}
  record Worker(String workerId){} record LeaseView(int attemptNo,String leaseToken){} record Event(String type,String payloadJson){} record Card(String messageType,String cardType,Map<String,Object> payload){} record Completion(UUID conversationId,String text,Card card,Map<String,Object> traceSummary,String memorySummary,Long memorySummaryThroughSequence){} record Waiting(UUID conversationId,String text,Card card,Map<String,Object> snapshot){} record CandidateCompletion(int size,List<UUID> seedArtistIds,String resultJson){} record ReportRef(UUID reportId){} record ReportCompletion(UUID reportId,String resultJson){} record ReportFailure(UUID reportId,String code,String message){} record Failure(String code,String message){}
  record InterventionCursor(long afterSequence){} record InterventionApplied(long throughSequence){} record InterventionBatch(List<InterventionView> items){} record InterventionView(long sequenceNumber,String type,String content,String status){static InterventionView of(com.indiesoundquest.agent.domain.AgentRunIntervention value){return new InterventionView(value.getSequenceNumber(),value.getType().name(),value.getContent(),value.getStatus().name());}}
}
