package com.indiesoundquest.agent.domain;
public enum AgentRunEventType { PLAN_UPDATED, PROGRESS, COMMENTARY, TOOL_STARTED, TOOL_COMPLETED, TOOL_DEGRADED, RESPONSE_STARTED, RESPONSE_DELTA, INTERVENTION_ACCEPTED, INTERVENTION_APPLIED, CLARIFICATION_REQUESTED, DEGRADED, RETRY, RESULT, FAILED, CANCELLED }
