package com.indiesoundquest.agent.domain;
public enum AgentRunEventType { PLAN_UPDATED, PROGRESS, TOOL_STARTED, TOOL_COMPLETED, TOOL_DEGRADED, CLARIFICATION_REQUESTED, DEGRADED, RETRY, RESULT, FAILED, CANCELLED }
