package com.indiesoundquest.tournament.application;
import com.fasterxml.jackson.databind.ObjectMapper; import com.indiesoundquest.tournament.domain.*; import com.indiesoundquest.tournament.repository.*; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class MusicPreferenceProfileService {
 private final MusicPreferenceProfileRepository profiles; private final TournamentRepository tournaments; private final TournamentEntryRepository entries; private final TournamentMatchRepository matches; private final VoteRepository votes; private final ObjectMapper json;
 public MusicPreferenceProfileService(MusicPreferenceProfileRepository profiles,TournamentRepository tournaments,TournamentEntryRepository entries,TournamentMatchRepository matches,VoteRepository votes,ObjectMapper json){this.profiles=profiles;this.tournaments=tournaments;this.entries=entries;this.matches=matches;this.votes=votes;this.json=json;}
 @Transactional public MusicPreferenceProfile refresh(GuestSession guest){var completed=tournaments.findByGuestSessionIdAndStatusAndDeletedAtIsNullOrderByCompletedAtAsc(guest.getId(),TournamentStatus.COMPLETED); var artistWins=new LinkedHashMap<String,Integer>(); var champions=new ArrayList<Map<String,String>>(); var choiceEvents=new ArrayList<Map<String,Object>>(); for(var t:completed){var tournamentEntries=entries.findByTournamentId(t.getId());var entryById=new HashMap<UUID,TournamentEntry>();tournamentEntries.forEach(e->entryById.put(e.getId(),e));for(var e:tournamentEntries) if(e.getId().equals(winnerId(t))){artistWins.merge(e.getArtistNameSnapshot(),1,Integer::sum);champions.add(Map.of("title",e.getTitleSnapshot(),"artistName",e.getArtistNameSnapshot()));}var tournamentMatches=matches.findByTournamentIdOrderByRoundNumberAscMatchIndexAsc(t.getId());var voteByMatch=new HashMap<UUID,Vote>();votes.findByMatchIdIn(tournamentMatches.stream().map(TournamentMatch::getId).toList()).forEach(v->voteByMatch.put(v.getMatchId(),v));for(var match:tournamentMatches){var vote=voteByMatch.get(match.getId());if(vote==null||match.getLeftEntryId()==null||match.getRightEntryId()==null)continue;var winner=entryById.get(vote.getSelectedEntryId());var loserId=vote.getSelectedEntryId().equals(match.getLeftEntryId())?match.getRightEntryId():match.getLeftEntryId();var loser=entryById.get(loserId);if(winner!=null&&loser!=null)choiceEvents.add(Map.of("eventType","TOURNAMENT_VOTE","tournamentId",t.getId().toString(),"matchId",match.getId().toString(),"round",match.getRoundNumber(),"winnerTitle",winner.getTitleSnapshot(),"winnerArtist",winner.getArtistNameSnapshot(),"loserTitle",loser.getTitleSnapshot(),"loserArtist",loser.getArtistNameSnapshot()));}}
  var observations=new ArrayList<Map<String,Object>>(); artistWins.forEach((artist,count)->observations.add(Map.of("name","艺人集中偏好","direction","preference","supportingTournamentCount",count,"status",count>=2?"STABLE":"EARLY","confidence",count>=3?"high":count>=2?"medium":"low","explanation",count>=2?"多场赛事的冠军或晋级路径反复指向"+artist+"。":"本场赛事暂时更常选择"+artist+"的作品。")));
  try{String body=json.writeValueAsString(Map.of("schemaVersion","2.0","tournamentCount",completed.size(),"stage",completed.size()>=3?"READY_FOR_REVIEW":"EARLY","observations",observations,"recentChampions",champions.subList(Math.max(0,champions.size()-3),champions.size()),"recentChoiceEvents",choiceEvents.subList(Math.max(0,choiceEvents.size()-96),choiceEvents.size()))); var p=profiles.findByGuestSessionId(guest.getId()).orElseGet(()->MusicPreferenceProfile.create(guest,body,completed.size())); p.refresh(body,completed.size()); return profiles.save(p);}catch(Exception e){throw new IllegalStateException("PROFILE_SERIALIZATION_FAILED",e);}}
 // Tournament currently exposes its winner through persisted matches; final completed match is authoritative.
 private UUID winnerId(Tournament t){return t.getWinnerEntryId();}
 @Transactional(readOnly=true) public Optional<MusicPreferenceProfile> get(GuestSession guest){return profiles.findByGuestSessionId(guest.getId());}
 @Transactional public void reset(GuestSession guest){profiles.deleteByGuestSessionId(guest.getId());}
 @Transactional public MusicPreferenceProfile settings(GuestSession guest,boolean enabled){var p=profiles.findByGuestSessionId(guest.getId()).orElseGet(()->refresh(guest));p.setUseForCandidateGeneration(enabled);return profiles.save(p);}
}
