package com.indiesoundquest.tournament.web;
import com.indiesoundquest.identity.GuestIdentityFilter; import com.indiesoundquest.tournament.application.TournamentApplicationService; import com.indiesoundquest.tournament.domain.*; import com.indiesoundquest.tournament.repository.*; import jakarta.servlet.http.HttpServletRequest; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.util.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1") public class TournamentController {
 private final ArtistRepository artists; private final RecordingRepository recordings; private final TournamentRepository tournaments; private final TournamentEntryRepository entries; private final TournamentMatchRepository matches; private final TournamentApplicationService service;
 public TournamentController(ArtistRepository artists,RecordingRepository recordings,TournamentRepository tournaments,TournamentEntryRepository entries,TournamentMatchRepository matches,TournamentApplicationService service){this.artists=artists;this.recordings=recordings;this.tournaments=tournaments;this.entries=entries;this.matches=matches;this.service=service;}
 @GetMapping("/artists") List<Map<String,Object>> artists(){return artists.findAllByOrderBySortNameAsc().stream().map(a->Map.<String,Object>of("id",a.getId(),"name",a.getName())).toList();}
 @PostMapping("/tournaments") ResponseEntity<Map<String,Object>> create(@Valid @RequestBody CreateTournament body,HttpServletRequest request){var artist=artists.findById(body.artistId()).orElseThrow();var list=recordings.findByArtistIdOrderBySeedRankAsc(artist.getId()).stream().limit(body.size()).toList();var t=service.createDraft(guest(request),artist,list,body.size());return ResponseEntity.status(HttpStatus.CREATED).body(Map.of("id",t.getId(),"status",t.getStatus()));}
 @GetMapping("/tournaments/{id}") @org.springframework.transaction.annotation.Transactional(readOnly=true) TournamentDetailResponse get(@PathVariable UUID id,HttpServletRequest r){var t=tournaments.findByIdAndGuestSessionIdAndDeletedAtIsNull(id,guest(r).getId()).orElseThrow();var all=matches.findByTournamentIdOrderByRoundNumberAscMatchIndexAsc(id);var dto=all.stream().map(TournamentDetailResponse.Match::from).toList();var current=dto.stream().filter(m->m.status()==MatchStatus.PENDING&&m.leftEntryId()!=null&&m.rightEntryId()!=null).findFirst().orElse(null);return new TournamentDetailResponse(id,t.getStatus(),t.getSize(),(int)all.stream().filter(m->m.getStatus()==MatchStatus.COMPLETED).count(),entries.findByTournamentId(id).stream().map(TournamentDetailResponse.Entry::from).toList(),dto,current);}
 @PatchMapping("/tournaments/{id}") Map<String,Object> prepare(@PathVariable UUID id,@RequestBody UpdateTournament body,HttpServletRequest r){var t=service.prepare(id,guest(r).getId());return Map.of("id",t.getId(),"status",t.getStatus());}
 @PostMapping("/tournament-matches/{id}/votes") Map<String,Object> vote(@PathVariable UUID id,@RequestHeader("Idempotency-Key") String key,@Valid @RequestBody VoteRequest body,HttpServletRequest r){var t=service.vote(id,body.selectedEntryId(),guest(r).getId(),key);return Map.of("tournamentId",t.getId(),"status",t.getStatus());}
 private GuestSession guest(HttpServletRequest r){return (GuestSession)r.getAttribute(GuestIdentityFilter.ATTRIBUTE);} record CreateTournament(@NotNull UUID artistId,@Min(16) @Max(32) int size){} record UpdateTournament(@NotBlank String status){} record VoteRequest(@NotNull UUID selectedEntryId){}
}
