package com.indiesoundquest.conversation.application;
import com.fasterxml.jackson.databind.*; import java.io.*; import java.net.URI; import java.net.http.*; import java.time.Duration; import java.util.*; import java.util.function.Consumer; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Component;
@Component public class ConversationAgentGateway {
 private final ObjectMapper json; private final String baseUrl,token; private final HttpClient client=HttpClient.newBuilder().version(HttpClient.Version.HTTP_1_1).connectTimeout(Duration.ofSeconds(5)).build(); public ConversationAgentGateway(ObjectMapper j,@Value("${agent.internal.base-url:http://agent-service:8000}") String b,@Value("${agent.internal.service-token}") String t){json=j;baseUrl=b;token=t;}
 public Result stream(Map<String,Object> body,UUID requestId,Consumer<Event> events){try{var request=HttpRequest.newBuilder(URI.create(baseUrl+"/internal/v1/workflows/conversation:stream")).timeout(Duration.ofSeconds(180)).header("Authorization","Bearer "+token).header("X-Request-Id",requestId.toString()).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body))).build();var response=client.send(request,HttpResponse.BodyHandlers.ofInputStream());if(response.statusCode()!=200)throw new IllegalStateException("AGENT_HTTP_"+response.statusCode());try(var lines=new BufferedReader(new InputStreamReader(response.body()))){String event=null,data=null,line;while((line=lines.readLine())!=null){if(line.startsWith("event: "))event=line.substring(7).trim();else if(line.startsWith("data: "))data=line.substring(6).trim();else if(line.isEmpty()){if(("progress".equals(event)||"plan_updated".equals(event))&&data!=null)events.accept(new Event(event,data));else if("result".equals(event)&&data!=null){var node=json.readTree(data);var card=node.path("cardIntent");return new Result(node.path("text").asText(),card.isMissingNode()||card.isNull()?null:new Card(card.path("messageType").asText(),card.path("cardType").asText(),json.writeValueAsString(card.path("payload"))));}else if("error".equals(event))throw new IllegalStateException("AGENT_WORKFLOW_ERROR");event=null;data=null;}}throw new IllegalStateException("AGENT_RESULT_MISSING");}}catch(Exception e){throw new IllegalStateException("conversation agent unavailable",e);}}
 public record Event(String type,String data){}
 public record Card(String messageType,String cardType,String payloadJson){}
 public record Result(String text,Card card){}
}
