package com.indiesoundquest.conversation.application;
import com.indiesoundquest.conversation.domain.*; import com.indiesoundquest.conversation.repository.*; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class ConversationApplicationService {
 private final ConversationRepository conversations; private final ConversationMessageRepository messages; private final ConversationAgentGateway agent; public ConversationApplicationService(ConversationRepository c,ConversationMessageRepository m,ConversationAgentGateway a){conversations=c;messages=m;agent=a;}
 @Transactional public Conversation create(UUID guestId){var c=conversations.save(new Conversation(UUID.randomUUID(),guestId,"新的音乐探索"));messages.save(ConversationMessage.system(c.getId(),"我们的歌曲世界杯应该从哪开始？描述一下你的音乐喜好，或告诉我最近反复听的歌。",1));return c;}
 @Transactional(readOnly=true) public List<Conversation> list(UUID guestId){return conversations.findByGuestSessionIdAndStatusNotOrderByLastMessageAtDesc(guestId,ConversationStatus.DELETED);}
 @Transactional(readOnly=true) public Conversation owned(UUID id,UUID guestId){return conversations.findByIdAndGuestSessionIdAndStatusNot(id,guestId,ConversationStatus.DELETED).orElseThrow(NoSuchElementException::new);}
 @Transactional(readOnly=true) public List<ConversationMessage> messages(UUID id,UUID guestId){owned(id,guestId);return messages.findByConversationIdOrderBySequenceNumberAsc(id);}
 @Transactional public Conversation rename(UUID id,UUID guestId,String title){var c=owned(id,guestId);c.rename(title);return c;}
 @Transactional public void archive(UUID id,UUID guestId){owned(id,guestId).archive();}
 @Transactional public void delete(UUID id,UUID guestId){owned(id,guestId).delete();}
 @Transactional public ConversationMessage card(UUID id,UUID guestId,UUID clientId,ConversationMessageType type,String cardType,String payload){owned(id,guestId);var existing=messages.findByConversationIdAndClientMessageId(id,clientId);if(existing.isPresent())return existing.get();long next=messages.findTopByConversationIdOrderBySequenceNumberDesc(id).map(x->x.getSequenceNumber()+1).orElse(1L);return messages.save(ConversationMessage.card(id,clientId,type,cardType,payload,next));}
 @Transactional public Turn begin(UUID id,UUID guestId,UUID clientMessageId,String content){var c=owned(id,guestId);var replay=messages.findByConversationIdAndClientMessageId(id,clientMessageId);if(replay.isPresent())return new Turn(replay.get(),null,true);long next=messages.findTopByConversationIdOrderBySequenceNumberDesc(id).map(x->x.getSequenceNumber()+1).orElse(1L);var user=messages.save(ConversationMessage.user(id,clientMessageId,content,next));if("新的音乐探索".equals(c.getTitle()))c.rename(content.substring(0,Math.min(36,content.length())));c.touch();var run=messages.save(ConversationMessage.run(id,UUID.randomUUID(),next+1));return new Turn(user,run,false);}
 @Transactional public ConversationMessage complete(UUID id,UUID runId,ConversationAgentGateway.Result result){var run=messages.findByConversationIdAndAgentRunId(id,runId).orElseThrow(NoSuchElementException::new);run.complete();messages.save(run);var response=messages.save(ConversationMessage.assistant(id,runId,result.text(),run.getSequenceNumber()+1));if(result.card()!=null){var type=ConversationMessageType.valueOf(result.card().messageType());if(type!=ConversationMessageType.CLARIFICATION_CARD&&type!=ConversationMessageType.TOURNAMENT_CARD&&type!=ConversationMessageType.RECOMMENDATION_CARD)throw new IllegalArgumentException("unsupported Agent card type");messages.save(ConversationMessage.card(id,UUID.randomUUID(),type,result.card().cardType(),result.card().payloadJson(),run.getSequenceNumber()+2));}conversations.findById(id).ifPresent(c->{c.touch();conversations.save(c);});return response;}
 @Transactional public void fail(UUID id,UUID runId){messages.findByConversationIdAndAgentRunId(id,runId).ifPresent(run->{run.fail();messages.save(run);});} public record Turn(ConversationMessage user,ConversationMessage run,boolean replayed){}
 public ConversationMessage reply(UUID id,UUID guestId,UUID clientMessageId,String content,java.util.function.Consumer<ConversationAgentGateway.Event> events){var turn=begin(id,guestId,clientMessageId,content);if(turn.replayed()){return messages(id,guestId).stream().filter(m->m.getType()==ConversationMessageType.AGENT_TEXT&&m.getSequenceNumber()>turn.user().getSequenceNumber()).findFirst().orElse(turn.user());}var transcript=messages(id,guestId);var start=Math.max(0,transcript.size()-12);var history=transcript.stream().filter(m->m.getTextContent()!=null).skip(start).map(m->Map.of("role",m.getRole().name(),"content",m.getTextContent())).toList();var conversation=owned(id,guestId);var body=Map.<String,Object>of("requestId",turn.run().getAgentRunId(),"agentRunId",turn.run().getAgentRunId(),"conversationId",id,"userMessage",content,"summary",conversation.getSummary()==null?"":conversation.getSummary(),"recentMessages",history,"confirmedMemories",List.of());try{return complete(id,turn.run().getAgentRunId(),agent.stream(body,turn.run().getAgentRunId(),events));}catch(RuntimeException e){fail(id,turn.run().getAgentRunId());throw e;}}
}
