package com.indiesoundquest.agent.application;
import com.fasterxml.jackson.databind.ObjectMapper; import com.indiesoundquest.agent.domain.*; import com.indiesoundquest.agent.repository.*; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class AgentRunApplicationService {
 private final AgentRunRepository runs; private final AgentRunEventRepository events; private final AgentRunAttemptRepository attempts; private final AgentRunInterventionRepository interventions; private final ObjectMapper json; private final AgentRunMetrics metrics;
 public AgentRunApplicationService(AgentRunRepository runs,AgentRunEventRepository events,AgentRunAttemptRepository attempts,AgentRunInterventionRepository interventions,ObjectMapper json,AgentRunMetrics metrics){this.runs=runs;this.events=events;this.attempts=attempts;this.interventions=interventions;this.json=json;this.metrics=metrics;}
 @Transactional public AgentRun create(UUID runId,UUID guestSessionId,UUID conversationId,AgentRunType runType){return runs.save(AgentRun.create(runId,guestSessionId,conversationId,runType));}
 @Transactional(readOnly=true) public AgentRun owned(UUID runId,UUID guestSessionId){return runs.findByIdAndGuestSessionId(runId,guestSessionId).orElseThrow(NoSuchElementException::new);}
 @Transactional(readOnly=true) public Optional<AgentRun> findOwned(UUID runId,UUID guestSessionId){return runs.findByIdAndGuestSessionId(runId,guestSessionId);}
 @Transactional public AgentRun createQueued(UUID runId,UUID guestSessionId,UUID conversationId,AgentRunType runType,String snapshot){var run=runs.save(AgentRun.queued(runId,guestSessionId,conversationId,runType,snapshot));metrics.created(runType);return run;}
 @Transactional public AgentRun createQueuedForTournament(UUID runId,UUID guestSessionId,UUID tournamentId,AgentRunType runType,String snapshot){var run=runs.save(AgentRun.queuedForTournament(runId,guestSessionId,tournamentId,runType,snapshot));metrics.created(runType);return run;}
 @Transactional(readOnly=true) public Optional<AgentRun> latestTournamentRun(UUID tournamentId,AgentRunType runType){return runs.findTopByTournamentIdAndRunTypeOrderByCreatedAtDesc(tournamentId,runType);}
 @Transactional public AgentRunEvent appendEvent(UUID runId,AgentRunEventType type,String payloadJson){var run=runs.findLockedById(runId).orElseThrow();return events.save(AgentRunEvent.create(runId,run.allocateEventSequence(),type,payloadJson));}
 @Transactional public void relaySseEvent(UUID runId,String sseType,String payloadJson){var mapped=switch(sseType){case "plan_updated"->AgentRunEventType.PLAN_UPDATED;case "progress"->AgentRunEventType.PROGRESS;default->null;};if(mapped!=null)appendEvent(runId,mapped,payloadJson);}
 @Transactional(readOnly=true) public List<AgentRunEvent> eventsAfter(UUID runId,UUID guestSessionId,long afterSequence){owned(runId,guestSessionId);return events.findByRunIdAndSequenceNumberGreaterThanOrderBySequenceNumberAsc(runId,afterSequence);}
 @Transactional public void markWaitingForUser(UUID runId,Map<String,Object> snapshot){var run=runs.findById(runId).orElseThrow();try{run.markWaitingForUser(json.writeValueAsString(snapshot));}catch(Exception e){throw new IllegalStateException("SNAPSHOT_SERIALIZATION_FAILED",e);}runs.save(run);appendEvent(runId,AgentRunEventType.CLARIFICATION_REQUESTED,run.getContextSnapshotJson());}
 @Transactional public void resume(UUID runId){var run=runs.findById(runId).orElseThrow();run.resume();runs.save(run);}
 @Transactional public void complete(UUID runId,String artifactJson){var run=runs.findLockedById(runId).orElseThrow();run.complete(artifactJson);runs.save(run);events.save(AgentRunEvent.create(runId,run.allocateEventSequence(),AgentRunEventType.RESULT,artifactJson==null?"{}":artifactJson));metrics.completed(run.getRunType(),java.time.Duration.between(run.getStartedAt(),java.time.Instant.now()));}
 @Transactional public void fail(UUID runId,String payloadJson){var run=runs.findById(runId).orElseThrow();run.fail();runs.save(run);appendEvent(runId,AgentRunEventType.FAILED,payloadJson);metrics.failed(run.getRunType());}
 @Transactional public AgentRun cancel(UUID runId,UUID guestSessionId){var run=runs.findLockedById(runId).orElseThrow();if(!run.getGuestSessionId().equals(guestSessionId))throw new NoSuchElementException();if(run.getStatus()==AgentRunStatus.COMPLETED||run.getStatus()==AgentRunStatus.FAILED||run.getStatus()==AgentRunStatus.CANCELLED||run.getStatus()==AgentRunStatus.EXPIRED)return run;attempts.findTopByRunIdOrderByAttemptNoDesc(runId).filter(attempt->"RUNNING".equals(attempt.getStatus())).ifPresent(attempt->{attempt.fail("USER_CANCELLED",java.time.Instant.now());attempts.save(attempt);});run.cancel();runs.save(run);events.save(AgentRunEvent.create(runId,run.allocateEventSequence(),AgentRunEventType.CANCELLED,"{\"phase\":\"cancelled\",\"message\":\"已停止本轮任务\"}"));return run;}
 @Transactional public Lease claim(UUID runId,String workerId){var run=runs.findLockedById(runId).orElseThrow();if(run.getStatus()!=AgentRunStatus.QUEUED)throw new IllegalStateException("AGENT_RUN_NOT_QUEUED");int no=attempts.findTopByRunIdOrderByAttemptNoDesc(runId).map(x->x.getAttemptNo()+1).orElse(1);String token=UUID.randomUUID().toString();var attempt=attempts.save(AgentRunAttempt.start(runId,no,workerId,token,java.time.Instant.now()));run.start();runs.save(run);appendEvent(runId,AgentRunEventType.PROGRESS,"{\"phase\":\"queued\",\"message\":\"Agent 已开始处理\"}");metrics.claimed(run.getRunType());return new Lease(no,token);}
 @Transactional public void heartbeat(UUID runId,String token){var attempt=attempts.findByRunIdAndLeaseToken(runId,token).orElseThrow();if(!attempt.valid(token,java.time.Instant.now()))throw new IllegalStateException("LEASE_LOST");attempt.heartbeat(java.time.Instant.now());attempts.save(attempt);}
 @Transactional public void assertLease(UUID runId,String token){var attempt=attempts.findByRunIdAndLeaseToken(runId,token).orElseThrow();if(!attempt.valid(token,java.time.Instant.now()))throw new IllegalStateException("LEASE_LOST");}
 @Transactional public AgentRunIntervention submitIntervention(UUID runId,UUID guestSessionId,UUID clientMessageId,String content){var run=runs.findLockedById(runId).orElseThrow();if(!run.getGuestSessionId().equals(guestSessionId))throw new NoSuchElementException();if(run.getConversationId()==null||!(run.getRunType()==AgentRunType.CONVERSATION||run.getRunType()==AgentRunType.EXPLORATION_REPORT))throw new IllegalStateException("AGENT_RUN_NOT_STEERABLE");if(!(run.getStatus()==AgentRunStatus.QUEUED||run.getStatus()==AgentRunStatus.RUNNING))throw new IllegalStateException("AGENT_RUN_NOT_ACTIVE");var replay=interventions.findByRunIdAndClientMessageId(runId,clientMessageId);if(replay.isPresent())return replay.get();long sequence=interventions.findTopByRunIdOrderBySequenceNumberDesc(runId).map(value->value.getSequenceNumber()+1).orElse(1L);var intervention=interventions.save(AgentRunIntervention.create(runId,run.getConversationId(),guestSessionId,clientMessageId,sequence,content));events.save(AgentRunEvent.create(runId,run.allocateEventSequence(),AgentRunEventType.INTERVENTION_ACCEPTED,write(Map.of("phase","direction_update","status","accepted","message","已收到你的补充，将在下一步调整计划","interventionSequence",sequence))));return intervention;}
 @Transactional(readOnly=true) public List<AgentRunIntervention> interventionsAfter(UUID runId,String token,long afterSequence){assertLease(runId,token);return interventions.findByRunIdAndSequenceNumberGreaterThanOrderBySequenceNumberAsc(runId,afterSequence);}
 @Transactional public int markInterventionsApplied(UUID runId,String token,long throughSequence){assertLease(runId,token);var run=runs.findLockedById(runId).orElseThrow();var values=interventions.findByRunIdAndSequenceNumberLessThanEqualOrderBySequenceNumberAsc(runId,throughSequence);int count=0;for(var value:values){if(value.getStatus()==AgentRunInterventionStatus.PENDING){value.markApplied();interventions.save(value);count++;}}if(count>0)events.save(AgentRunEvent.create(runId,run.allocateEventSequence(),AgentRunEventType.INTERVENTION_APPLIED,write(Map.of("phase","direction_update","status","applied","message","正在根据你的补充调整计划","interventionSequence",throughSequence,"appliedCount",count))));return count;}
 @Transactional public void finishLease(UUID runId,String token){var attempt=attempts.findByRunIdAndLeaseToken(runId,token).orElseThrow();if(!attempt.valid(token,java.time.Instant.now()))throw new IllegalStateException("LEASE_LOST");attempt.complete(java.time.Instant.now());attempts.save(attempt);}
 @Transactional public void retry(UUID runId,String token,String code){var now=java.time.Instant.now();var attempt=attempts.findByRunIdAndLeaseToken(runId,token).orElseThrow();if(!attempt.valid(token,now))throw new IllegalStateException("LEASE_LOST");attempt.fail(code,now);attempts.save(attempt);var run=runs.findLockedById(runId).orElseThrow();run.retry();runs.save(run);appendEvent(runId,AgentRunEventType.RETRY,"{\"phase\":\"retry\",\"message\":\"Agent 正在重试本次任务\"}");metrics.retry(code);}
 @Transactional public void expireLease(UUID runId,String token){var now=java.time.Instant.now();var attempt=attempts.findByRunIdAndLeaseToken(runId,token).orElseThrow();if(!"RUNNING".equals(attempt.getStatus())||attempt.getLeaseExpiresAt().isAfter(now))return;attempt.fail("LEASE_EXPIRED",now);attempts.save(attempt);var run=runs.findLockedById(runId).orElseThrow();if(run.getStatus()==AgentRunStatus.RUNNING){run.retry();runs.save(run);appendEvent(runId,AgentRunEventType.RETRY,"{\"phase\":\"recovery\",\"message\":\"Worker 中断，正在恢复任务\"}");metrics.retry("LEASE_EXPIRED");}}
 @Transactional(readOnly=true) public List<AgentRunAttempt> expiredLeases(){return attempts.findTop50ByStatusAndLeaseExpiresAtLessThanEqualOrderByLeaseExpiresAtAsc("RUNNING",java.time.Instant.now());}
 private String write(Object value){try{return json.writeValueAsString(value);}catch(Exception e){throw new IllegalStateException("AGENT_EVENT_SERIALIZATION_FAILED",e);}}
 public record Lease(int attemptNo,String leaseToken){}
}
