import { useRef, useState, type CSSProperties, type ReactNode, type RefObject } from 'react'
import { toPng } from 'html-to-image'
import { completedDate, deriveTournamentResult, roundLabel, type ResultEntry, type ResultMatch, type ResultTournament } from './tournamentResult'
import { playbackLabel, type PlaybackState } from './listening'
import './tournament-result.css'

type Props = { tournament: ResultTournament; playbackFor: (recordingId: string) => PlaybackState; onPreview: (recordingId: string) => void; onPrefetch: (recordingId: string) => void; onGenerateReport: () => void; reportLoading: boolean; hasReadyReport: boolean; onNewTournament: () => void; children?: ReactNode }

export function TournamentResultView({ tournament, playbackFor, onPreview, onPrefetch, onGenerateReport, reportLoading, hasReadyReport, onNewTournament, children }: Props) {
  const result = deriveTournamentResult(tournament); const exportRef = useRef<HTMLElement>(null); const [exporting, setExporting] = useState(false); const [previewUrl, setPreviewUrl] = useState<string | null>(null)
  async function createPreview() { if (!exportRef.current) return; setExporting(true); try { setPreviewUrl(await toPng(exportRef.current, { backgroundColor: '#fdf9f4', pixelRatio: 2, cacheBust: true })) } catch { window.alert('赛事长图生成失败，请稍后重试。') } finally { setExporting(false) } }
  function download() { if (!previewUrl) return; const link = document.createElement('a'); link.href = previewUrl; link.download = `indie-sound-quest-tournament-${tournament.id.slice(0, 8)}.png`; link.click() }
  return <section className="tournament-result"><article className="result-hero"><p className="eyebrow">赛事结果 · {tournament.size} 首歌曲世界杯</p><p className="result-date">{completedDate(tournament.completedAt)}</p><ResultSong entry={result.champion} featured playback={result.champion ? playbackFor(result.champion.recordingId) : undefined} onPreview={onPreview} onPrefetch={onPrefetch}/><div className="result-summary"><span>冠军</span><strong>{result.champion?.title || '结果生成中'}</strong><small>{result.champion?.artistName}</small></div></article><div className="result-actions"><button className="primary" disabled={reportLoading} onClick={onGenerateReport}>{reportLoading ? '正在分析你的选择…' : hasReadyReport ? '重新生成本场报告' : '生成本场偏好报告'}</button><button className="secondary" disabled={exporting} onClick={() => void createPreview()}>{exporting ? '正在生成赛事长图…' : '预览赛事长图'}</button><button className="text-action" onClick={onNewTournament}>再办一场</button></div><TournamentBracket tournament={tournament} exportMode={false}/>{children}<TournamentExport tournament={tournament} exportRef={exportRef}/>{previewUrl && <div className="export-modal" role="dialog" aria-modal="true" aria-label="赛事长图预览"><div><button className="modal-close" onClick={() => setPreviewUrl(null)}>关闭</button><img src={previewUrl} alt="歌曲世界杯赛事长图预览"/><button className="primary" onClick={download}>下载 PNG 长图</button></div></div>}</section>
}

function ResultSong({ entry, featured, playback, onPreview, onPrefetch }: { entry?: ResultEntry; featured?: boolean; playback?: PlaybackState; onPreview?: (id: string) => void; onPrefetch?: (id: string) => void }) {
  if (!entry) return null
  const content = <>{entry.coverUrl ? <img crossOrigin="anonymous" src={entry.coverUrl} alt={`${entry.albumTitle || entry.title} 封面`}/> : <div className="result-art-placeholder">ISQ</div>}<span><strong>{entry.title}</strong><small>{entry.artistName}</small>{playback && <em className={`playback-state ${playback.phase}`}>{playbackLabel(playback.phase)}</em>}</span></>
  return onPreview ? <article className={`result-song ${featured ? 'featured' : ''}`}><button onClick={() => onPreview(entry.recordingId)} onMouseEnter={() => onPrefetch?.(entry.recordingId)} onFocus={() => onPrefetch?.(entry.recordingId)} aria-label={`试听 ${entry.artistName}的${entry.title}`}>{content}</button><a href={entry.listeningSearchUrl} target="_blank" rel="noreferrer">去网易云搜索</a></article> : <article className={`result-song ${featured ? 'featured' : ''}`}>{content}</article>
}

function MatchCard({ match, byId, championMatchIds }: { match: ResultMatch; byId: Map<string, ResultEntry>; championMatchIds: Set<string> }) { const winner = match.winnerEntryId ? byId.get(match.winnerEntryId) : undefined; return <article className={`bracket-match ${championMatchIds.has(match.id) ? 'champion-route' : ''}`}><div>{match.leftEntryId ? byId.get(match.leftEntryId)?.title : '待定'}{winner?.id === match.leftEntryId && <b>胜</b>}</div><div>{match.rightEntryId ? byId.get(match.rightEntryId)?.title : '待定'}{winner?.id === match.rightEntryId && <b>胜</b>}</div></article> }

function TournamentBracket({ tournament, exportMode }: { tournament: ResultTournament; exportMode: boolean }) { const result = deriveTournamentResult(tournament); const byId = new Map(tournament.entries.map(entry => [entry.id, entry])); const split = (round: ResultMatch[]) => { const half = Math.ceil(round.length / 2); return [round.slice(0, half), round.slice(half)] as const }; const leftRounds = result.rounds.slice(0, -1).map(round => split(round)[0]); const rightRounds = result.rounds.slice(0, -1).map(round => split(round)[1]); return <section className={exportMode ? 'bracket-export' : 'bracket-panel'}><div className="bracket-title"><p className="eyebrow">完整淘汰赛程</p><h2>从两边聚拢，留下这一首。</h2></div><div className="desktop-bracket"><BracketHalf rounds={leftRounds} reverse={false} byId={byId} championMatchIds={result.championMatchIds}/><div className="bracket-center"><p>决赛</p>{result.finalMatch && <MatchCard match={result.finalMatch} byId={byId} championMatchIds={result.championMatchIds}/>}<div className="bracket-champion"><span>本场冠军</span><strong>{result.champion?.title}</strong><small>{result.champion?.artistName}</small></div></div><BracketHalf rounds={rightRounds} reverse byId={byId} championMatchIds={result.championMatchIds}/></div><div className="mobile-bracket">{result.rounds.map((round, index) => <details key={index} open={index === result.rounds.length - 1}><summary>{roundLabel(index + 1, result.maxRound)} · {round.length} 场</summary>{round.map(match => <MatchCard key={match.id} match={match} byId={byId} championMatchIds={result.championMatchIds}/>)}</details>)}</div><div className="finalists"><span>亚军 · {result.runnerUp?.title || '—'}</span>{result.fourFinalists.map(entry => <span key={entry.id}>四强 · {entry.title}</span>)}</div></section> }

function BracketHalf({ rounds, reverse, byId, championMatchIds }: { rounds: ResultMatch[][]; reverse: boolean; byId: Map<string, ResultEntry>; championMatchIds: Set<string> }) { const rendered = reverse ? [...rounds].reverse() : rounds; return <div className={`bracket-half ${reverse ? 'right-half' : 'left-half'}`} style={{ '--columns': rounds.length } as CSSProperties}>{rendered.map((round, index) => <div className="bracket-round" key={`${reverse}-${index}`}><span>{reverse ? `第 ${rounds.length - index} 轮` : `第 ${index + 1} 轮`}</span><div>{round.map(match => <MatchCard key={match.id} match={match} byId={byId} championMatchIds={championMatchIds}/>)}</div></div>)}</div> }

function TournamentExport({ tournament, exportRef }: { tournament: ResultTournament; exportRef: RefObject<HTMLElement> }) { const result = deriveTournamentResult(tournament); return <article className="tournament-export" ref={exportRef}><p className="eyebrow">IndieSoundQuest · {tournament.size} 首歌曲世界杯</p><h1>这一场，最后留下的是</h1><ResultSong entry={result.champion} featured/><p className="export-result-meta">亚军 · {result.runnerUp?.title || '—'}　 四强 · {result.fourFinalists.map(entry => entry.title).join(' · ')}</p><TournamentBracket tournament={tournament} exportMode/><footer>IndieSoundQuest</footer></article> }
