ALTER TABLE recording
  ADD COLUMN cover_url VARCHAR(2048) NULL,
  ADD COLUMN cover_source VARCHAR(32) NOT NULL DEFAULT 'NONE',
  ADD COLUMN cover_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  ADD COLUMN cover_fetched_at TIMESTAMP(3) NULL;
